version: "3.9"

services:
  todo_app_dev:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./todo_app
        target: /todo_app
  todo_app_test:
    build:
      context: ./
      dockerfile: Dockerfile
      target: test
    volumes:
      - type: bind
        source: ./todo_app
        target: /todo_app