version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017

  todo-app-prod:
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    ports:
      - 5200:5000
    env_file:
      - ./.env
  todo-app-dev:
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    ports:
      - 5100:5000
    env_file: 
      - ./.env
    volumes:
      - type: bind
        source: ./todoapp
        target: /app/todoapp

  todo-app-unittests:
    build:
      target: unittests
      context: .
      dockerfile: Dockerfile

  todo-app-integrationtests:
    build:
      target: integrationtests
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.test

  todo-app-endtoendtests:
    build:
      target: endtoendtests
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env

    