version: "3.8"

services:
  todo_app:
    container_name: todo_app
    build:
      context: .
      target: development
    env_file:
      - .env
    ports:
    - 5000:5000
    volumes:
    - type: bind
      source: ./todo_app
      target: /app/todo_app
      read_only: true
  todo_app_tests:
    container_name: todo_app_tests
    image: todo-app:test
    volumes:
    - type: bind
      source: ./todo_app
      target: /app/todo_app
      read_only: true
