version: '3.9'

services:
  dev:
    build: 
      context: .
      target: development

    ports:
      - 5000:5000
      
    env_file:
      ./.env
    volumes:
      - ./todo-app:/app/todo_app 


  selenium:
    build: 
      context: .
      target: development
      
    ports:
        - 5000:5000
    volumes:
        - ./todo-app:/app/todo_app 
    privileged: true