#!/bin/bash
DOCKER_REPO=todo-app
echo "Building and pushing docker image to docker hub"
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build --target production -t $DOCKER_USERNAME/$DOCKER_REPO .
docker push $DOCKER_USERNAME/$DOCKER_REPO
#:$TRAVIS_COMMIT