version: "3"

services:
  todo_app:
    container_name: todo_app
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: todo-app:dev
    env_file:
      - .env
    ports:
    - 5000:5000
    volumes:
    - ".:/app"