
import pytest
import json
from todo_app.data.classes import Card, List


class dummy_api:

    def get_cards():
        """
        dummy cards data generated by running curl command
        curl -X GET "https://api.trello.com/1/boards/5f71a0d7bc65981011e221ad/cards?key=&token=
        """

        cards = """
        [{"id":"5f835afcf6400f7c70f9597e","checkItemStates":null,"closed":false,"dateLastActivity":"2020-10-11T19:20:28.624Z","desc":"This is a test task for a new item","descData":null,"dueReminder":null,"idBoard":"5f71a0d7bc65981011e221ad","idList":"5f71a0d7bc65981011e221af","idMembersVoted":[],"idShort":63,"idAttachmentCover":null,"idLabels":[],"manualCoverAttachment":false,"name":"New Test Task","pos":32768,"shortLink":"iUihslfg","isTemplate":false,"badges":{"attachmentsByType":{"trello":{"board":0,"card":0}},"location":false,"votes":0,"viewingMemberVoted":false,"subscribed":false,"fogbugz":"","checkItems":0,"checkItemsChecked":0,"checkItemsEarliestDue":null,"comments":0,"attachments":0,"description":true,"due":"2020-10-30T00:00:00.000Z","dueComplete":false,"start":null},"dueComplete":false,"due":"2020-10-30T00:00:00.000Z","idChecklists":[],"idMembers":[],"labels":[],"shortUrl":"https://trello.com/c/iUihslfg","start":null,"subscribed":false,"url":"https://trello.com/c/iUihslfg/63-new-test-task","cover":{"idAttachment":null,"color":null,"idUploadedBackground":null,"size":"normal","brightness":"light"}},
            {"id":"5f835bddf343bc27dedf776b","checkItemStates":null,"closed":false,"dateLastActivity":"2020-10-11T19:24:19.312Z","desc":"This is a second test task for a new item","descData":{"emoji":{}},"dueReminder":null,"idBoard":"5f71a0d7bc65981011e221ad","idList":"5f71a0d7bc65981011e221b0","idMembersVoted":[],"idShort":64,"idAttachmentCover":null,"idLabels":[],"manualCoverAttachment":false,"name":"New Test Task 2","pos":49152,"shortLink":"NpehcnOb","isTemplate":false,"badges":{"attachmentsByType":{"trello":{"board":0,"card":0}},"location":false,"votes":0,"viewingMemberVoted":false,"subscribed":false,"fogbugz":"","checkItems":0,"checkItemsChecked":0,"checkItemsEarliestDue":null,"comments":0,"attachments":0,"description":true,"due":"2020-10-29T00:00:00.000Z","dueComplete":false,"start":null},"dueComplete":false,"due":"2020-10-29T00:00:00.000Z","idChecklists":[],"idMembers":[],"labels":[],"shortUrl":"https://trello.com/c/NpehcnOb","start":null,"subscribed":false,"url":"https://trello.com/c/NpehcnOb/64-new-test-task-2","cover":{"idAttachment":null,"color":null,"idUploadedBackground":null,"size":"normal","brightness":"light"}}]
        """
        return json.loads(cards)

    def get_card():
        """
        dummy card data generated by running curl command
        curl -X GET "https://api.trello.com/1/cards/5f835afcf6400f7c70f9597e?key=&token="
        """
        card = """
        {"id":"5f835afcf6400f7c70f9597e","checkItemStates":[],"closed":false,"dateLastActivity":"2020-10-11T19:20:28.624Z","desc":"This is a test task for a new item","descData":null,"dueReminder":null,"idBoard":"5f71a0d7bc65981011e221ad","idList":"5f71a0d7bc65981011e221af","idMembersVoted":[],"idShort":63,"idAttachmentCover":null,"idLabels":[],"manualCoverAttachment":false,"name":"New Test Task","pos":32768,"shortLink":"iUihslfg","isTemplate":false,"dueComplete":false,"due":"2020-10-30T00:00:00.000Z","labels":[],"shortUrl":"https://trello.com/c/iUihslfg","start":null,
            "url":"https://trello.com/c/iUihslfg/63-new-test-task","cover":{"idAttachment":null,"color":null,"idUploadedBackground":null,"size":"normal","brightness":"light"},"idMembers":[],"email":null,"badges":{"attachmentsByType":{"trello":{"board":0,"card":0}},"location":false,"votes":0,"viewingMemberVoted":false,"subscribed":false,"fogbugz":"","checkItems":0,"checkItemsChecked":0,"checkItemsEarliestDue":null,"comments":0,"attachments":0,"description":true,"due":"2020-10-30T00:00:00.000Z","dueComplete":false,"start":null},"subscribed":false,"idChecklists":[]}
        """
        return json.loads(card)

    def get_lists():
        """
        dummy list data generated by running curl command
        curl -X GET "https://api.trello.com/1/boards/5f71a0d7bc65981011e221ad/lists?key=&token="
        """
        lists = """
        [{"id":"5f71a0d7bc65981011e221af","name":"TODO","closed":false,"pos":131071,"softLimit":null,"idBoard":"5f71a0d7bc65981011e221ad","subscribed":false},{"id":"5f71a0d7bc65981011e221b0","name":"DOING","closed":false,"pos":196607,"softLimit":null,"idBoard":"5f71a0d7bc65981011e221ad","subscribed":false},{"id":"5f71a0d7bc65981011e221b1","name":"DONE","closed":false,"pos":262143,"softLimit":null,"idBoard":"5f71a0d7bc65981011e221ad","subscribed":false}]
        """
        return json.loads(lists)


@pytest.fixture
def card():
    # setup()
    dummy_card = dummy_api.get_card()
    dummy_lists = [List(k, i) for i, k in enumerate(dummy_api.get_lists())]
    card = Card(dummy_lists, dummy_card)
    yield card


def test_card_id(card):
    assert card.id == "5f835afcf6400f7c70f9597e"


@pytest.fixture
def lists():
    # setup()
    lists = [List(k, i) for i, k in enumerate(dummy_api.get_lists())][0]
    yield lists


def test_list(lists):
    assert lists.id == "5f71a0d7bc65981011e221af"
