name: Continuous Integration

on:

   push:                    # Will make the workflow run every time you push to any branch

    paths-ignore:

    - '**/README.md'

   pull_request:

    paths-ignore:

    - '**/README.md'

jobs:

    job-one:
      name: Build and test
      runs-on: ubuntu-latest     # Sets the build environment a machine with the latest Ubuntu installed
      steps:
      - uses: actions/checkout@v2  # Adds a step to checkout the repository code
   
      - name: Build Docker
        run: docker build --tag todo-app:devtestpy --target devtestpy .


      - name: Run Docker
        run: docker run -e FLASK_APP=${{ secrets.FLASK_APP}} -e FLASK_ENV=${{ secrets.FLASK_ENV}} -e SECRET_KEY=${{ secrets.SECRET_KEY }} todo-app:devtestpy

    job-two:
      name: image build & push
      runs-on: ubuntu-latest
      needs: job-one
      steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          target: prodpy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest 
      
    job-three:
      name: Deploy Heroku
      runs-on: ubuntu-latest
      needs: [job-one, job-two]
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Deploy to Heroku
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
            usedocker: true
            